import type { Metadata } from "next";
import { PT_Mono, Gento } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

// const mono = PT_Mono({  subsets:["latin"], weight: ["400"] });

// const myFontMono = localFont({ src: '../fonts/PTMono.ttc' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      {/* <body className={myFontMono.className}> */}
      <body>
        <Header/>
          {children}
        <Footer/>
        </body>
    </html>
  );
}
